"""Registry of every KPI: key -> metadata used by the definitions page,
README, and compute_all. Every KpiValue key must exist here and vice versa
(enforced by a test)."""

DEFINITIONS: dict[str, dict] = {
    # Throughput
    "sessions_completed": {
        "group": "Throughput",
        "label": "Sessions completed",
        "formula": "Count of sessions with a terminal status in period "
        "(status is exit or suspended — anything not running)",
        "source": "sessions list",
        "depends_on": [],
    },
    "prs_created": {
        "group": "Throughput",
        "label": "PRs created",
        "formula": "Count of session PRs whose session was created in period",
        "source": "sessions pull_requests[]",
        "depends_on": [],
    },
    "prs_merged": {
        "group": "Throughput",
        "label": "PRs merged",
        "formula": "PRs created with pr_state merged",
        "source": "sessions pull_requests[]",
        "depends_on": [],
    },
    "prs_closed_unmerged": {
        "group": "Throughput",
        "label": "PRs closed unmerged",
        "formula": "PRs created with pr_state closed but not merged",
        "source": "sessions pull_requests[]",
        "depends_on": [],
    },
    "merge_rate": {
        "group": "Throughput",
        "label": "Merge rate",
        "formula": "prs_merged / prs_created",
        "source": "sessions pull_requests[]",
        "depends_on": [],
    },
    "sessions_shipped_rate": {
        "group": "Throughput",
        "label": "Sessions that shipped",
        "formula": "sessions with >=1 merged PR / sessions created",
        "source": "sessions + pull_requests[]",
        "depends_on": [],
    },
    "human_takeover_rate": {
        "group": "Throughput",
        "label": "Human takeover rate",
        "formula": "prs_taken_over_count / prs_created_count",
        "source": "metrics/prs snapshot",
        "depends_on": [],
    },
    # Cycle time
    "request_to_merge_median": {
        "group": "Cycle time",
        "label": "Request to merged change (median)",
        "formula": "median(merged_at - session.created_at) over merged PRs",
        "source": "session_prs (git enrichment)",
        "depends_on": ["git_enrichment"],
    },
    "request_to_merge_p90": {
        "group": "Cycle time",
        "label": "Request to merged change (p90)",
        "formula": "p90(merged_at - session.created_at) over merged PRs",
        "source": "session_prs (git enrichment)",
        "depends_on": ["git_enrichment"],
    },
    "session_duration_median": {
        "group": "Cycle time",
        "label": "Session duration (median)",
        "formula": "median(updated_at - created_at) over terminal sessions",
        "source": "sessions list",
        "depends_on": [],
    },
    "session_duration_p90": {
        "group": "Cycle time",
        "label": "Session duration (p90)",
        "formula": "p90(updated_at - created_at) over terminal sessions",
        "source": "sessions list",
        "depends_on": [],
    },
    "pr_open_to_merge_median": {
        "group": "Cycle time",
        "label": "PR open to merge (median)",
        "formula": "median(merged_at - pr_created_at) over merged PRs",
        "source": "session_prs (git enrichment)",
        "depends_on": ["git_enrichment"],
    },
    "pr_open_to_merge_p90": {
        "group": "Cycle time",
        "label": "PR open to merge (p90)",
        "formula": "p90(merged_at - pr_created_at) over merged PRs",
        "source": "session_prs (git enrichment)",
        "depends_on": ["git_enrichment"],
    },
    # Cost
    "acus_per_session_mean": {
        "group": "Cost",
        "label": "ACUs per session (mean)",
        "formula": "mean(acus_consumed)",
        "source": "sessions list",
        "depends_on": [],
    },
    "acus_per_session_median": {
        "group": "Cost",
        "label": "ACUs per session (median)",
        "formula": "median(acus_consumed)",
        "source": "sessions list",
        "depends_on": [],
    },
    "acus_per_merged_pr": {
        "group": "Cost",
        "label": "ACUs per merged PR",
        "formula": "sum(acus_consumed) / merged PR count",
        "source": "sessions + pull_requests[]",
        "depends_on": [],
    },
    "cost_per_merged_pr": {
        "group": "Cost",
        "label": "Cost per merged PR",
        "formula": "acus_per_merged_pr * ACU_UNIT_PRICE",
        "source": "config",
        "depends_on": ["ACU_UNIT_PRICE"],
    },
    "cost_per_session": {
        "group": "Cost",
        "label": "Cost per session",
        "formula": "acus_per_session_mean * ACU_UNIT_PRICE",
        "source": "config",
        "depends_on": ["ACU_UNIT_PRICE"],
    },
    "cost_per_story_point": {
        "group": "Cost",
        "label": "Cost per story point",
        "formula": "sum(acus of sessions w/ pointed issues) / sum(story_points) * ACU_UNIT_PRICE",
        "source": "session_issues (tracker enrichment)",
        "depends_on": ["tracker_enrichment", "ACU_UNIT_PRICE"],
    },
    "acus_per_story_point": {
        "group": "Cost",
        "label": "ACUs per story point",
        "formula": "sum(acus of sessions w/ pointed issues) / sum(story_points)",
        "source": "session_issues (tracker enrichment)",
        "depends_on": ["tracker_enrichment"],
    },
    "total_acus": {
        "group": "Cost",
        "label": "Total ACUs",
        "formula": "sum(acus_consumed)",
        "source": "sessions list",
        "depends_on": [],
    },
    "total_cost": {
        "group": "Cost",
        "label": "Total spend",
        "formula": "total_acus * ACU_UNIT_PRICE",
        "source": "sessions + config",
        "depends_on": ["ACU_UNIT_PRICE"],
    },
    # Adoption
    "dau": {
        "group": "Adoption",
        "label": "DAU",
        "formula": "distinct human users with >=1 session on the period's last day "
        "(excludes service users and code_scan/automation origins)",
        "source": "sessions list",
        "depends_on": [],
    },
    "wau": {
        "group": "Adoption",
        "label": "WAU",
        "formula": "distinct human users with >=1 session in the 7 days ending at the "
        "period end (trailing window; not clipped by the period start)",
        "source": "sessions list",
        "depends_on": [],
    },
    "mau": {
        "group": "Adoption",
        "label": "MAU",
        "formula": "distinct human users with >=1 session in the 30 days ending at the "
        "period end (trailing window; not clipped by the period start)",
        "source": "sessions list",
        "depends_on": [],
    },
    "stickiness": {
        "group": "Adoption",
        "label": "Stickiness (DAU/MAU)",
        "formula": "DAU / MAU",
        "source": "sessions list",
        "depends_on": [],
    },
    "active_vs_licensed": {
        "group": "Adoption",
        "label": "Active users vs licensed",
        "formula": "distinct human users active in period / SEAT_COUNT",
        "source": "sessions + config SEAT_COUNT",
        "depends_on": ["SEAT_COUNT"],
    },
    "playbook_automation_share": {
        "group": "Adoption",
        "label": "Playbook & automation share",
        "formula": "sessions with playbook_id or automation_id / all sessions",
        "source": "sessions list",
        "depends_on": [],
    },
    # Quality & efficiency
    "large_session_share": {
        "group": "Quality & efficiency",
        "label": "L/XL session share",
        "formula": "sessions with size L or XL / sized sessions",
        "source": "session_insights.session_size",
        "depends_on": [],
    },
    "user_messages_per_session": {
        "group": "Quality & efficiency",
        "label": "User messages per session",
        "formula": "mean(num_user_messages)",
        "source": "session_insights",
        "depends_on": [],
    },
    "closed_without_merge_rate": {
        "group": "Quality & efficiency",
        "label": "Closed-without-merge rate",
        "formula": "prs_closed_unmerged / prs_created",
        "source": "sessions pull_requests[]",
        "depends_on": [],
    },
    "review_comments_per_merged_pr": {
        "group": "Quality & efficiency",
        "label": "Review comments per merged PR",
        "formula": "mean(review_comments) over merged PRs",
        "source": "session_prs (git enrichment)",
        "depends_on": ["git_enrichment"],
    },
    "review_rounds_per_merged_pr": {
        "group": "Quality & efficiency",
        "label": "Review rounds per merged PR",
        "formula": "mean(review_rounds) over merged PRs",
        "source": "session_prs (git enrichment)",
        "depends_on": ["git_enrichment"],
    },
    "usage_limit_hit_rate": {
        "group": "Quality & efficiency",
        "label": "Sessions stopped by usage limit",
        "formula": "sessions with status_detail in (usage_limit_exceeded, "
        "org_usage_limit_exceeded, user_usage_limit_exceeded) / sessions created",
        "source": "sessions list (status_detail)",
        "depends_on": [],
    },
    "session_error_rate": {
        "group": "Quality & efficiency",
        "label": "Sessions ended in error",
        "formula": "sessions with status_detail error / sessions created",
        "source": "sessions list (status_detail)",
        "depends_on": [],
    },
}
